#!/bin/bash
NAME=$1

if [ -z $NAME ]; then
  echo "usage: init <PROJECT_NAME>"
  exit 1
fi

REPO_PATH="$HOME/$NAME.git"
PROJECT_PATH="$HOME/$NAME"

[[ -d $REPO_PATH ]] && rm -rf "$REPO_PATH"
[[ -d $PROJECT_PATH ]] && rm -rf "$PROJECT_PATH"

mkdir "$REPO_PATH"
mkdir "$PROJECT_PATH"

pushd "$REPO_PATH" || exit
git init --bare
popd || exit

cat <<EOF >"$REPO_PATH/hooks/post-receive"
#!/bin/bash
git --git-dir $REPO_PATH --work-tree $PROJECT_PATH checkout -f "\$@"
EOF

chmod +x "$REPO_PATH"/hooks/post-receive

touch "$HOME/git"
chmod +x "$HOME/git"

cat <<EOF >"$HOME/git"
#!/bin/bash
git --git-dir $REPO_PATH --work-tree $PROJECT_PATH "\$@"
EOF

